server:
  port: 9092

logging:
  level:
    org.springframework: info

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client:
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://test"
              scopes:
                - "openid"
                - "profile"
                - "user.read"
                - "user.write"
            require-authorization-consent: false
  flyway:
    enabled: true
    validate-on-migrate: true
    mixed: true
  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: postgres
    password: smartcode
    hikari:
      schema: property_report
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    hibernate.show-sql: true

  jwt:
    secret:
      key: MkxlSlVEUllLdGJXUG1EdnlqakR4d09iYlRXRm5XM0w=

  common:
    mail:
      sender: kiplimocollins855@gmail.com