server:
  port: 9092

logging:
  level:
    org.springframework: info

spring:
  flyway:
    enabled: true
    validate-on-migrate: true
    mixed: true
  datasource:
    url: jdbc:postgresql://localhost:5432/property
    username: postgres
    password: smartcode
    hikari:
      schema: property_report
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    hibernate.show-sql: true